stage_init: minor-clean-ups

diff --git a/stage_init.in b/stage_init.in
--- a/stage_init.in
+++ b/stage_init.in
@@ -37,12 +37,12 @@ EOF
 fi
 
 test -n "$BUILD_ID" -a -n "$REPORTS_DIR" # who knows...
-rm -rf $REPORT1_DIR
-mkdir -p -m 700 $tmpdir
+rm -rf "$REPORT1_DIR"
+mkdir -p -m 700 "$tmpdir"
 cp "$ICON_FILE" "$REPORT1_DIR/distbb.ico"
 cp "$CSS_FILE" "$REPORT1_DIR/distbb.css"
 
-echo "$build_start" > $build_start_fn
+echo "$build_start" > "$build_start_fn"
 
 tmp_stderr_fn="$tmpdir/tmp_stderr"
 
@@ -71,13 +71,13 @@ summary2PKGPATH (){
 # main
 verbose_print "Preparations\n"
 
-printf '' > $packages_failed_notavail_fn.tmp
-printf '' > $packages_failed_scan_fn
-printf '' > $packages_failed_deps_fn
-printf '' > $packages_failed_fn.tmp
-printf '' > $packages_built_prev_fn
+printf '' > "$packages_failed_notavail_fn.tmp"
+printf '' > "$packages_failed_scan_fn"
+printf '' > "$packages_failed_deps_fn"
+printf '' > "$packages_failed_fn.tmp"
+printf '' > "$packages_built_prev_fn"
 
-printf '' > $progress_fn
+printf '' > "$progress_fn"
 
 ######################################################################
 ### unpacking bootstrap
@@ -300,8 +300,8 @@ NF == 0 {print pkgpath "," pkgbase}
 summary2PKGPATH "$pkg_src_summary_fn" |
 sort -u > "$tmpdir/all_src_pkgpaths.tmp"
 
-all_deps_PAeNA_fn=$tmpdir/all_deps_PAeNA.tmp
-all_bin_summary_fn=$tmpdir/all_bin_summary.tmp
+all_deps_PAeNA_fn="$tmpdir/all_deps_PAeNA.tmp"
+all_bin_summary_fn="$tmpdir/all_bin_summary.tmp"
 if is_true "$CROSS_COMPILE"; then
     add_BH_prefix1 "$PKG_ALL_SUMMARY" > "$all_bin_summary_fn"
     add_BH_prefix2 "$TARGET_PKG_ALL_SUMMARY" >> "$all_bin_summary_fn"
@@ -345,7 +345,7 @@ printf '' > "$summary_cmp_fn"
 # rebuilt previously
 PAeNA2PAe "$tmpdir/packages_PAeNA.tmp" | sort -u > "$tmpdir/packages_PAe.tmp"
 
-changed_pkgs_fn=$tmpdir/changed.tmp
+changed_pkgs_fn="$tmpdir/changed.tmp"
 awk 'NF == 3 {print $2 "\n" $3; next}
      NF == 1 {print}' "$rebuild_PAe_fn" |
 sort -u > "$changed_pkgs_fn"
@@ -364,7 +364,7 @@ eval @libexecdir@/wrapper \
     $PKG_CMP_SUMMARY_CMD "$pkg_src_summary_fn" "$PKG_ALL_SUMMARY" \
     > "$summary_cmp_fn" || true
 
-grep '^<' $summary_cmp_fn > "$tmp_stderr_fn" || true
+grep '^<' "$summary_cmp_fn" > "$tmp_stderr_fn" || true
 if test -s "$tmp_stderr_fn"; then
     cat >> "$errors_fn" <<'EOF'
 ------------------
